# Generated by Django 3.1 on 2021-06-07 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkPointMng.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Throughput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('throughput', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TerminalThroughput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('throughput', models.IntegerField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkPointMng.airport')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkPointMng.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='AirportThroughput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('throughput', models.IntegerField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkPointMng.airport')),
            ],
        ),
    ]
