# Generated by Django 3.1 on 2021-06-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0002_airport_airportthroughput_terminal_terminalthroughput_throughput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportthroughput',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='terminalthroughput',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='throughput',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
