# Generated by Django 3.1.6 on 2021-06-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0004_lasday'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasday',
            name='twentyNineteen',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='lasday',
            name='twentyTwenty',
            field=models.NullBooleanField(),
        ),
    ]
