# Generated by Django 3.1.6 on 2021-06-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0006_auto_20210618_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasday',
            name='twentyNineteen',
            field=models.BooleanField(default=False, verbose_name='2019'),
        ),
        migrations.AlterField(
            model_name='lasday',
            name='twentyTwenty',
            field=models.BooleanField(default=False, verbose_name='2020'),
        ),
    ]
