# Generated by Django 3.1.6 on 2021-06-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0007_auto_20210618_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasday',
            name='terminal',
            field=models.CharField(choices=[('1', 'Terminal 1'), ('2', 'Terminal 2'), ('3', 'Terminal 3')], default='1', max_length=20),
        ),
    ]
