# Generated by Django 3.1.6 on 2021-06-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0008_auto_20210618_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasday',
            name='day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default='1', max_length=9),
        ),
        migrations.AlterField(
            model_name='lasday',
            name='terminal',
            field=models.CharField(choices=[('1', 'Term 1 - AB'), ('2', 'Term 1 - C'), ('3', 'Term 1 - CX'), ('4', 'Term 1 - D'), ('5', 'Terminal 3 - E Lower (1)'), ('6', 'Terminal 3 - E Upper')], default='1', max_length=20),
        ),
    ]
