# Generated by Django 3.1.6 on 2021-06-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0010_auto_20210618_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lasday',
            name='year',
        ),
        migrations.AddField(
            model_name='lasday',
            name='twentyEighteen',
            field=models.BooleanField(default=False, verbose_name='2018'),
        ),
        migrations.AddField(
            model_name='lasday',
            name='twentySeventeen',
            field=models.BooleanField(default=False, verbose_name='2017'),
        ),
        migrations.AddField(
            model_name='lasday',
            name='twentySixteen',
            field=models.BooleanField(default=False, verbose_name='2016'),
        ),
    ]
