# Generated by Django 3.1.6 on 2021-06-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0011_auto_20210618_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasday',
            name='terminal',
            field=models.CharField(choices=[('Term 1 - AB', 'Term 1 - AB'), ('Term 1 - C', 'Term 1 - C'), ('Term 1 - CX', 'Term 1 - CX'), ('Term 1 - D', 'Term 1 - D'), ('Terminal 3 - E Lower (1)', 'Terminal 3 - E Lower (1)'), ('Terminal 3 - E Upper', 'Terminal 3 - E Upper')], max_length=24),
        ),
    ]
