# Generated by Django 3.1.6 on 2021-06-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0013_auto_20210618_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasday',
            name='twentyFifteen',
            field=models.BooleanField(default=False, verbose_name='2015'),
        ),
    ]
