# Generated by Django 3.1.6 on 2021-06-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0015_laxday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laxday',
            name='twentyEighteen',
        ),
        migrations.RemoveField(
            model_name='laxday',
            name='twentyFifteen',
        ),
        migrations.RemoveField(
            model_name='laxday',
            name='twentyNineteen',
        ),
        migrations.RemoveField(
            model_name='laxday',
            name='twentySeventeen',
        ),
        migrations.RemoveField(
            model_name='laxday',
            name='twentySixteen',
        ),
        migrations.RemoveField(
            model_name='laxday',
            name='twentyTwenty',
        ),
    ]
