# Generated by Django 3.1.6 on 2021-06-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0016_auto_20210623_2313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LASDay',
        ),
    ]
