# Generated by Django 3.1.6 on 2021-06-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0018_laxmonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAXYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(choices=[('Suites', 'Suites'), ('TBIT Main Checkpoint', 'TBIT Main Checkpoint'), ('Terminal 1 - Passenger', 'Terminal 1 - Passenger'), ('Terminal 2 - Passenger', 'Terminal 2 - Passenger'), ('Terminal 3 - Passenger', 'Terminal 3 - Passenger'), ('Terminal 4 - FIS', 'Terminal 4 - FIS'), ('Terminal 4 - Passenger', 'Terminal 4 - Passenger'), ('Terminal 4a - Passenger', 'Terminal 4a - Passenger'), ('Terminal 5 - Passenger', 'Terminal 5 - Passenger'), ('Terminal 5a - Passenger', 'Terminal 5a - Passenger'), ('Terminal 6 - Passenger', 'Terminal 6 - Passenger'), ('Terminal 7 - Passenger', 'Terminal 7 - Passenger')], max_length=23)),
                ('primaryYear', models.CharField(choices=[('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015')], max_length=4)),
            ],
        ),
    ]
