# Generated by Django 3.1.6 on 2021-06-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0020_auto_20210626_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laxday',
            old_name='primary',
            new_name='start',
        ),
        migrations.AddField(
            model_name='laxday',
            name='end',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
