# Generated by Django 3.1.6 on 2021-07-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0022_lasday'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHXDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(choices=[('T-2', 'T-2'), ('T-3 NORTH', 'T-3 NORTH'), ('T-4 A', 'T-4 A'), ('T-4 B', 'T-4 B'), ('T-4 C', 'T-4 C'), ('T-4 D', 'T-4 D')], max_length=9)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
