# Generated by Django 3.1.6 on 2021-07-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkPointMng', '0023_phxday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laxday',
            name='terminal',
            field=models.CharField(choices=[('Suites', 'Suites'), ('TBIT Main Checkpoint', 'TBIT Main Checkpoint'), ('Terminal 1 - Passenger', 'Terminal 1 - Passenger'), ('Terminal 2 - Passenger', 'Terminal 2 - Passenger'), ('Terminal 3 - Passenger', 'Terminal 3 - Passenger'), ('Terminal 4 - FIS', 'Terminal 4 - FIS'), ('Terminal 4 - Passenger', 'Terminal 4 - Passenger'), ('Terminal 4a - Passenger', 'Terminal 4a - Passenger'), ('Terminal 5 - Passenger', 'Terminal 5 - Passenger'), ('Terminal 5a - Passenger', 'Terminal 5a - Passenger'), ('Terminal 6 - Passenger', 'Terminal 6 - Passenger'), ('Terminal 7 - Passenger', 'Terminal 7 - Passenger')], max_length=24),
        ),
        migrations.AlterField(
            model_name='phxday',
            name='terminal',
            field=models.CharField(choices=[('T-2', 'T-2'), ('T-3 NORTH', 'T-3 NORTH'), ('T-4 A', 'T-4 A'), ('T-4 B', 'T-4 B'), ('T-4 C', 'T-4 C'), ('T-4 D', 'T-4 D')], max_length=24),
        ),
    ]
